homme(odilon).
homme(roger).
homme(vincent).
homme(arnaud).
homme(marcel).
homme(blaise).
homme(edouard).
homme(marius).
femme(genevieve).
femme(melanie).
femme(roseline).
femme(paule).
femme(agnes).
femme(martine).
femme(pauline).
femme(tatiana).
femme(prisca).
couple(1,odilon,genevieve).
couple(2,roger,melanie).
couple(3,edouard,tatiana).
couple(4,vincent,roseline).
couple(5,marcel,paule).
enfant(pauline,1).
enfant(melanie,1).
enfant(edouard,1).
enfant(roseline,2).
enfant(marcel,2).
enfant(marius,3).
enfant(prisca,3).
enfant(agnes,4).
enfant(arnaud,4).
enfant(martine,5).
enfant(blaise,5).
pere(X,Y):-enfant(Y,X),homme(X).
mere(X,Y):-enfant(Y,X),femme(X).
soeur(X,Y):-enfant(X,Z),enfant(Y,Z),femme(X).
frere(X,Y):-enfant(X,Z),enfant(Y,Z),homme(X).
frere_ou_soeur(X,Y):-enfant(X,couple(Z)),enfant(X,couple(Z)).
oncle(X,Y):-enfant(Y,Z),frere(X,Z).
tante(X,Y):-enfant(Y,Z),soeur(X,Z).
grand_parent(X,Y):-enfant(Y,Z),enfant(Z,X).
cousin_cousine(X,Y):-tante(Z,X),enfant(Y,Z);oncle(Z,X),enfant(X,Z).
